version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000" # Zakładając, że backend działa na porcie 8000
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000" # Zakładając, że frontend działa na porcie 3000